# -*- coding: utf-8 -*-
"""llama with sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17e-9xK0MKIoNGNBntFNw8ZXawJ30PCRK
"""

!pip install transformers
!huggingface-cli login

!pip install -U bitsandbytes

# Load model directly
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import BitsAndBytesConfig
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm



# Load product data from CSV
df = pd.read_csv(r"/content/drive/MyDrive/Research/Prd_template_api_call.csv")

# Configuration for loading in 4-bit
bnb_config = BitsAndBytesConfig(load_in_4bit=True)

# Load tokenizer and model with 4-bit quantization
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.1-8B-Instruct")
model = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Llama-3.1-8B-Instruct",
    quantization_config=bnb_config,
    device_map="auto"  # Automatically maps the model to available GPUs/CPUs
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Custom dataset class
class ProductDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        row = self.dataframe.iloc[idx]
        return row["Product Name"], row["Category"], row["About Product"]

# Function to generate product descriptions
def generate_description(product_name, product_category,about_product):
    prompt = (
    f"Write a product description for the following product:\n"
    f"Product Name: {product_name}\n"
    f"Product Category: {product_category}\n"
    f"About the Product: {about_product}\n\n"
    "Keep the description concise and engaging, highlighting key features in a consumer-friendly tone. "
    "Do not include unnecessary headers or editorial comments."
    "Example:\n"
    "Adorable Iwako Japanese Vehicle & Plane Eraser Set! Fun and functional erasers perfect for kids, "
    "students, and collectors. These high-quality erasers feature detailed designs of various vehicles and planes. "
    "Great for school, office, or creative projects. Shop now!"
)
    # Encode the prompt text into tensor format
    inputs = tokenizer.encode(prompt, return_tensors="pt").to(device)

    # Generate text using the model
    outputs = model.generate(
        inputs,
        max_length=500,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        temperature=0.7
    )

    # Decode the generated output and clean the response
    description = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Remove the prompt text from the output (the first line)
    description = description.replace(prompt, '').strip()

    return description

# Prepare DataLoader for batch processing
data_loader = DataLoader(ProductDataset(df), batch_size=1, shuffle=False)

# Generate descriptions with tqdm for progress tracking
descriptions = []

for product_name, product_category, about_product in tqdm(data_loader, desc="Generating Descriptions"):
    product_name = product_name[0]  # Extract string from batch
    product_category = product_category[0]  # Extract string from batch
    about_product = about_product[0]
    description = generate_description(product_name, product_category,about_product)
    descriptions.append(description)

# Add descriptions to the DataFrame
df["Description"] = descriptions

# Save the descriptions back to a new CSV
output_file = "/content/drive/MyDrive/Research/llama_results_with_sample.csv"
df.to_csv(output_file, index=False)
print(f"Descriptions generated and saved to {output_file}!")